#!/opt/perl/bin/perl

use 5.028;

use strict;
use warnings;
no  warnings 'syntax';

use experimental 'signatures';

foreach my $n (1 .. 10, 24, 100) {
    my $x = (3 * $n ** 4 + 2 * $n ** 3 - 3 * $n ** 2 - 2 * $n) / 12;
    say "$n -> $x";
}

__END__
