Row 1: \*hdc in next -1 stitches, 2 hdc in next stitch\* 100 times (100 stitches).
Row 2: \*hdc in next 0 stitches, 2 hdc in next stitch\* 100 times (200 stitches).
Row 3: \*hdc in next 1 stitches, 2 hdc in next stitch\* 100 times (300 stitches).
Row 4: \*hdc in next 2 stitches, 2 hdc in next stitch\* 100 times (400 stitches).
Row 5: \*hdc in next 3 stitches, 2 hdc in next stitch\* 100 times (500 stitches).
Row 6: \*hdc in next 4 stitches, 2 hdc in next stitch\* 100 times (600 stitches).
