#!/opt/perl/bin/perl

use 5.026;

use strict;
use warnings;
no  warnings 'syntax';

use           experimental 'signatures';
no  warnings 'experimental::signatures';

#
# 48 characters in the body.
#
sub n {@_[grep{2*$_[$_]<=$_[$_-1]+$_[($_+1)%@_]}0..$#_]}

while (<DATA>) {
    my @n = /-?[0-9]+/g;
    my @m = n @n;
    local $" = ", ";
    say "[@n] -> [@m]";
}

__DATA__
6, 9, 4, 10, 16, 18, 13
5, -8, -9
8, 8, 8, 8
11, 6, 9, 10
1, 2, 0, 1, 2
6, 9, 4, 10, 16, 18, 13
6, -5, 3, -4, 38, 29, 82, -44, 12
