#!/opt/perl/bin/perl

use 5.028;

use strict;
use warnings;
no  warnings 'syntax';

use experimental 'signatures';

while (<>) {
    chomp;
    my %h;
    @h{split//}=();
    say if keys(%h) < 8;
}

__END__
