#!/opt/perl/bin/perl

use 5.026;

use strict;
use warnings;
no  warnings 'syntax';

use experimental 'signatures';

use List::Util qw [max];

foreach my $ext (qw [pl]) {
    my $solution       = "solution.$ext";
    my $solution_hflip = "solution-hflip.$ext";
    my $solution_vflip = "solution-vflip.$ext";
    my $solution_dflip = "solution-dflip.$ext";

    open my $fh, "<", $solution or die "open: $!";

    my @lines = <$fh>;
    chomp @lines;

    #
    # Find the longest line, space pad the shorter ones.
    #
    my $max = max map {length} @lines;
    foreach my $line (@lines) {
        $line .= " " x ($max - length $line);
    }

    {
        open my $fh_hflip, ">", $solution_hflip or die "open: $!";
        open my $fh_vflip, ">", $solution_vflip or die "open: $!";
        open my $fh_dflip, ">", $solution_dflip or die "open: $!";
        foreach my $line (@lines) {
            say $fh_hflip scalar reverse $line;
        }
        foreach my $line (reverse @lines) {
            say $fh_vflip $line;
            say $fh_dflip scalar reverse $line;
        }
        close $fh_hflip;
        close $fh_vflip;
        close $fh_dflip;
    }
}


__END__
